In [1]:
"""
    使用TimeStamp
    1)提取时间多尺度
    2)计算时间diff
"""
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
train = pd.read_csv('./train.csv')
test1 = pd.read_csv('./test1.csv')
train

,Unnamed: 0,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,label,lan,media_id,...,os,osv,package,sid,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,0,316361,1199,46000.0,0.0,0.0,0.0,1,NaN,104,...,android,9,18,1438873,1.559893e+12,8,2135019403,0,2329670524,601
1,1,135939,893,0.0,0.0,0.0,0.0,1,NaN,19,...,android,8.1,0,1185582,1.559994e+12,4,2782306428,1,2864801071,1000
2,2,399254,821,0.0,760.0,0.0,360.0,1,NaN,559,...,android,8.1.0,0,1555716,1.559837e+12,0,1392806005,2,628911675,696
3,3,68983,1004,46000.0,2214.0,0.0,1080.0,0,NaN,129,...,android,8.1.0,0,1093419,1.560042e+12,0,3562553457,3,1283809327,753
4,4,288999,1076,46000.0,2280.0,0.0,1080.0,1,zh-CN,64,...,android,8.0.0,0,1400089,1.559867e+12,5,2364522023,4,1510695983,582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,499995,392477,1028,46000.0,1920.0,3.0,1080.0,1,zh-CN,144,...,Android,7.1.2,25,1546078,1.559834e+12,7,861755946,79,140647032,373
499996,499996,346134,1001,0.0,1424.0,0.0,720.0,0,NaN,29,...,android,8.1.0,0,1480612,1.559814e+12,3,1714444511,23,2745131047,525
499997,499997,499635,761,46000.0,1280.0,0.0,720.0,0,NaN,54,...,android,6.0.1,9,1698442,1.559676e+12,0,3843262581,25,1326115882,810
499998,499998,239786,917,46001.0,960.0,0.0,540.0,0,zh_CN,109,...,android,5.1.1,0,1331155,1.559840e+12,0,1984296118,225,1446741112,772
499999,499999,270531,929,46000.0,2040.0,3.0,1080.0,1,zh-CN,59,...,Android,8.1.0,78,1373973,1.559922e+12,5,1697301943,49,1915763579,1076

In [3]:
features = train.drop(['Unnamed: 0','label'],axis = 1)
labels = train['label']

In [4]:
#类别特征
cate_features = ['apptype','carrier','ntt','version','location','cus_type']
#不需要入模'os'（实际是唯一的，都是安卓）,'lan','sid'
remove_list = ['os','lan','sid']
col = features.columns.tolist()
for i in remove_list:
    col.remove(i)
col

['android_id',
 'apptype',
 'carrier',
 'dev_height',
 'dev_ppi',
 'dev_width',
 'media_id',
 'ntt',
 'osv',
 'package',
 'timestamp',
 'version',
 'fea_hash',
 'location',
 'fea1_hash',
 'cus_type']

In [5]:
#特征筛选
features = features[col]
features

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,media_id,ntt,osv,package,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,316361,1199,46000.0,0.0,0.0,0.0,104,6.0,9,18,1.559893e+12,8,2135019403,0,2329670524,601
1,135939,893,0.0,0.0,0.0,0.0,19,6.0,8.1,0,1.559994e+12,4,2782306428,1,2864801071,1000
2,399254,821,0.0,760.0,0.0,360.0,559,0.0,8.1.0,0,1.559837e+12,0,1392806005,2,628911675,696
3,68983,1004,46000.0,2214.0,0.0,1080.0,129,2.0,8.1.0,0,1.560042e+12,0,3562553457,3,1283809327,753
4,288999,1076,46000.0,2280.0,0.0,1080.0,64,2.0,8.0.0,0,1.559867e+12,5,2364522023,4,1510695983,582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,392477,1028,46000.0,1920.0,3.0,1080.0,144,6.0,7.1.2,25,1.559834e+12,7,861755946,79,140647032,373
499996,346134,1001,0.0,1424.0,0.0,720.0,29,2.0,8.1.0,0,1.559814e+12,3,1714444511,23,2745131047,525
499997,499635,761,46000.0,1280.0,0.0,720.0,54,6.0,6.0.1,9,1.559676e+12,0,3843262581,25,1326115882,810
499998,239786,917,46001.0,960.0,0.0,540.0,109,2.0,5.1.1,0,1.559840e+12,0,1984296118,225,1446741112,772
499999,270531,929,46000.0,2040.0,3.0,1080.0,59,2.0,8.1.0,78,1.559922e+12,5,1697301943,49,1915763579,1076

In [6]:
import time  #python底层日期函数
from datetime import datetime  #高级封装接口
print(features['timestamp'][0]/1000)
print(time.time())
print(datetime.fromtimestamp(1615081589.8722358))

1559892728.2417212
1615214183.279559
2021-03-07 09:46:29.872236

In [7]:
def get_date(features):
    #除以1000，转换为日期格式
    features['timestamp'] = features['timestamp'].apply(lambda x:datetime.fromtimestamp(x/1000))
    
    #创建时间戳索引
    temp = pd.DatetimeIndex(features['timestamp'])
    features['year'] = temp.year
    features['month'] = temp.month
    features['day'] = temp.day
    features['week_day'] = temp.weekday
    features['hour'] = temp.hour
    features['minute'] = temp.minute

    #添加time_diff
    start_time = features['timestamp'].min()
    features['time_diff'] = features['timestamp'] - start_time
    
    #将time_diff转换为小时
    features['time_diff'] = features['time_diff'].dt.days * 24 +features['time_diff'].dt.seconds/3600
    #Thinking：需不需要这么多特征？
    #使用day，time_diff
    features.drop(['timestamp','year','month','minute','week_day'],axis = 1,inplace = True)
    return features

In [8]:
#对训练集提取时间多尺度
features = get_date(features)
#对测试集提取时间多尺度
test1 = get_date(test1)
features

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,media_id,ntt,osv,package,version,fea_hash,location,fea1_hash,cus_type,day,hour,time_diff
0,316361,1199,46000.0,0.0,0.0,0.0,104,6.0,9,18,8,2135019403,0,2329670524,601,7,15,111.535278
1,135939,893,0.0,0.0,0.0,0.0,19,6.0,8.1,0,4,2782306428,1,2864801071,1000,8,19,139.671944
2,399254,821,0.0,760.0,0.0,360.0,559,0.0,8.1.0,0,0,1392806005,2,628911675,696,6,23,95.971111
3,68983,1004,46000.0,2214.0,0.0,1080.0,129,2.0,8.1.0,0,0,3562553457,3,1283809327,753,9,8,152.993333
4,288999,1076,46000.0,2280.0,0.0,1080.0,64,2.0,8.0.0,0,5,2364522023,4,1510695983,582,7,8,104.472222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,392477,1028,46000.0,1920.0,3.0,1080.0,144,6.0,7.1.2,25,7,861755946,79,140647032,373,6,23,95.238056
499996,346134,1001,0.0,1424.0,0.0,720.0,29,2.0,8.1.0,0,3,1714444511,23,2745131047,525,6,17,89.681111
499997,499635,761,46000.0,1280.0,0.0,720.0,54,6.0,6.0.1,9,0,3843262581,25,1326115882,810,5,3,51.248889
499998,239786,917,46001.0,960.0,0.0,540.0,109,2.0,5.1.1,0,0,1984296118,225,1446741112,772,7,0,96.990556
499999,270531,929,46000.0,2040.0,3.0,1080.0,59,2.0,8.1.0,78,5,1697301943,49,1915763579,1076,7,23,119.545833

In [9]:
#features2['day'].value_counts()

In [10]:
#features2['week_day'].value_counts()

In [11]:
#features2['year'].value_counts() #无意义，删除

In [12]:
#features2['month'].value_counts()  #无意义

In [13]:
#对osv进行特征编码LabelEncoder
#还可以转换为Float,需要数据清洗
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#需要将训练集和测试集合并，然后统一做LabelEncoder
all_df = pd.concat([train,test1])
all_df['osv'] = all_df['osv'].astype('str')
all_df['osv'] = le.fit_transform(all_df['osv'])

In [14]:
# 对于数值过大的异常值，设置为0
features['fea_hash'] = features['fea_hash'].map(lambda x: 0 if len(str(x))>16 else int(x))
features['fea1_hash'] = features['fea1_hash'].map(lambda x: 0 if len(str(x))>16 else int(x))

In [15]:
#对数据清洗，将V3=>3,V1=>1,V6=>6,V2=>2
#针对version，非数值类型 设置0
features['version'] = features['version'].map(lambda x: int(x) if str(x).isdigit() else 0)
features['osv'] = all_df[all_df['label'].notnull()]['osv']

In [16]:
import lightgbm as lgb
# 使用LightGBM训练
# 相比XGBoost的改进：对类别特征的处理，不需要one-hot
clf = lgb.LGBMClassifier()
clf.fit(features,labels,categorical_feature = cate_features)

LGBMClassifier()

In [17]:
#测试集做预测,保持与features中的columns一致
test_fea = test1[features.columns]

test_fea['fea_hash'] = test_fea['fea_hash'].map(lambda x: 0 if len(str(x))>16 else int(x))
test_fea['fea1_hash'] = test_fea['fea1_hash'].map(lambda x: 0 if len(str(x))>16 else int(x))

test_fea['version'] = test_fea['version'].map(lambda x: int(x) if str(x).isdigit() else 0)
test_fea['osv'] = all_df[all_df['label'].isnull()]['osv']

In [18]:
a = pd.DataFrame(test1['sid'])
a['label'] =  clf.predict(test_fea)
a.to_csv('version3.csv',index = False)

In [19]:
features[['day','time_diff']]

        day   time_diff
0         7  111.535278
1         8  139.671944
2         6   95.971111
3         9  152.993333
4         7  104.472222
...     ...         ...
499995    6   95.238056
499996    6   89.681111
499997    5   51.248889
499998    7   96.990556
499999    7  119.545833

[500000 rows x 2 columns]

In [20]:
a

            sid  label
0       1440682      0
1       1606824      1
2       1774642      0
3       1742535      0
4       1689686      1
...         ...    ...
149995  1165373      1
149996  1444115      1
149997  1134378      1
149998  1700238      1
149999  1201539      1

[150000 rows x 2 columns]